### ISSUE TITLE
You've got DB_NAME and DB_USER switched up 😸 

### ISSUE THREAD

**Issue by Nader-Sl** [manoj-wpzonify/backuplift#1]
In both **profile** and **profile-compressed** scripts:

`wpmysqluser=$(grep -w "DB_NAME" $target_dir/wp-config.php | cut --delimiter="'"  --fields="4")`
`wpmysqldb=$(grep -w "DB_USER" $target_dir/wp-config.php | cut --delimiter="'"  --fields="4")`

**Comment by manoj-lk-code** [comment]
Nice catch. I've updated it just now. Thank you ✌🙌
